<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 5.2.2deb1+deb13u1
 */

/**
 * Database `samfarm_db`
 */

/* `samfarm_db`.`proveedores` */
$proveedores = array(
  array('pr_id' => '10','pr_razon_social' => 'DULCIFARMA S.R.L.'),
  array('pr_id' => '11','pr_razon_social' => 'MEDICPACK'),
  array('pr_id' => '12','pr_razon_social' => 'UNIVERSAL PHARMA'),
  array('pr_id' => '13','pr_razon_social' => 'SANAT PHARMA SRL'),
  array('pr_id' => '14','pr_razon_social' => 'PORTUGAL'),
  array('pr_id' => '15','pr_razon_social' => 'RAICES IMPORT EXPORT LTDA'),
  array('pr_id' => '16','pr_razon_social' => 'MEDICPACK'),
  array('pr_id' => '17','pr_razon_social' => 'SAE S.A.'),
  array('pr_id' => '18','pr_razon_social' => 'TOR TRADE ON ROUTE S.R.L.'),
  array('pr_id' => '19','pr_razon_social' => 'LAFAR S.A.'),
  array('pr_id' => '20','pr_razon_social' => 'DREAMS FACTORY'),
  array('pr_id' => '21','pr_razon_social' => 'ALFA LTDA.'),
  array('pr_id' => '22','pr_razon_social' => 'DROGUERIA INTI S.A.'),
  array('pr_id' => '23','pr_razon_social' => 'LAQFAGA S.R.L.'),
  array('pr_id' => '24','pr_razon_social' => 'TELCHI - LITEL'),
  array('pr_id' => '25','pr_razon_social' => 'DELTA S.A.'),
  array('pr_id' => '26','pr_razon_social' => 'DISTRIBUIDORA UNION'),
  array('pr_id' => '27','pr_razon_social' => 'KRISHPAR CARE BOLIVIA S.R.L.'),
  array('pr_id' => '28','pr_razon_social' => 'LATINMED'),
  array('pr_id' => '29','pr_razon_social' => 'MEGA VIT'),
  array('pr_id' => '30','pr_razon_social' => 'QUIMFA BOLIVIA S.A.'),
  array('pr_id' => '31','pr_razon_social' => 'LABOFTA'),
  array('pr_id' => '32','pr_razon_social' => 'TERBOL S.A.(LAB.TERAPEUTICA BOLIVIANA SA)'),
  array('pr_id' => '33','pr_razon_social' => 'FARAON S.R.L.'),
  array('pr_id' => '34','pr_razon_social' => 'BAGO DE BOLIVIA S.A.'),
  array('pr_id' => '35','pr_razon_social' => 'MEGALABS'),
  array('pr_id' => '36','pr_razon_social' => 'PHARMA SERVICE REPRESENTANTES'),
  array('pr_id' => '37','pr_razon_social' => 'FARAON'),
  array('pr_id' => '38','pr_razon_social' => 'DISTRIBUIDORA CAYAÁN'),
  array('pr_id' => '39','pr_razon_social' => 'IMFAR S.R.L'),
  array('pr_id' => '40','pr_razon_social' => 'LABORATORIOS REX'),
  array('pr_id' => '41','pr_razon_social' => 'FARMAX'),
  array('pr_id' => '42','pr_razon_social' => 'IFARBO LTDA.'),
  array('pr_id' => '43','pr_razon_social' => 'INMEDENT S.R.L.'),
  array('pr_id' => '44','pr_razon_social' => 'INMEDENT SRL'),
  array('pr_id' => '45','pr_razon_social' => 'IMFAR S.R.L.'),
  array('pr_id' => '46','pr_razon_social' => 'ENGELS MERKEL & CIA (BOLIVIA) S.A'),
  array('pr_id' => '47','pr_razon_social' => 'MINERVA S.R.L.'),
  array('pr_id' => '48','pr_razon_social' => 'TELCHI LITEL'),
  array('pr_id' => '49','pr_razon_social' => 'KEOPS'),
  array('pr_id' => '50','pr_razon_social' => 'PHARMA SERVICE REPRESENTANTES'),
  array('pr_id' => '51','pr_razon_social' => 'COFAR S.A.'),
  array('pr_id' => '52','pr_razon_social' => 'SANAT PHARMA SRL'),
  array('pr_id' => '53','pr_razon_social' => 'TOTAL MEDIK'),
  array('pr_id' => '54','pr_razon_social' => 'LABORATORIOS VITA S.A.'),
  array('pr_id' => '55','pr_razon_social' => 'RODAMEDD'),
  array('pr_id' => '56','pr_razon_social' => 'DISFARMA'),
  array('pr_id' => '57','pr_razon_social' => 'COLHER GROUP S.R.L'),
  array('pr_id' => '58','pr_razon_social' => 'PHARMAGEN S.R.L.'),
  array('pr_id' => '59','pr_razon_social' => 'CORPORACION CHELESPHARMACEUTICALS S.R.L.'),
  array('pr_id' => '60','pr_razon_social' => 'SIGMA CORP SRL'),
  array('pr_id' => '61','pr_razon_social' => 'PROMEDICAL S.A.'),
  array('pr_id' => '62','pr_razon_social' => 'HP MEDICAL'),
  array('pr_id' => '63','pr_razon_social' => 'GRAMON BOLIVIA LTDA.'),
  array('pr_id' => '64','pr_razon_social' => 'D-IMPORT'),
  array('pr_id' => '65','pr_razon_social' => 'QUIMIZA LTDA.'),
  array('pr_id' => '66','pr_razon_social' => 'GRUPO ALCOS S.A.'),
  array('pr_id' => '67','pr_razon_social' => 'IFA S.A.'),
  array('pr_id' => '68','pr_razon_social' => 'PIGEON'),
  array('pr_id' => '69','pr_razon_social' => 'CASA PIEL'),
  array('pr_id' => '70','pr_razon_social' => 'ILLAMPU'),
  array('pr_id' => '71','pr_razon_social' => 'HIPOCRATES PHARMA'),
  array('pr_id' => '72','pr_razon_social' => 'TELCHI - LITEL'),
  array('pr_id' => '73','pr_razon_social' => 'DISPROMED S.R.L.'),
  array('pr_id' => '74','pr_razon_social' => 'BLANCO & NEGRO'),
  array('pr_id' => '75','pr_razon_social' => 'VISIONFARMA S.R.L.'),
  array('pr_id' => '76','pr_razon_social' => 'RAICES IMPORT EXPORT LTDA.'),
  array('pr_id' => '77','pr_razon_social' => 'LCFARMA S.R.L.'),
  array('pr_id' => '78','pr_razon_social' => 'PHARMAGEN  S.R.L.'),
  array('pr_id' => '79','pr_razon_social' => 'FARMEDICAL S.R.L.'),
  array('pr_id' => '80','pr_razon_social' => 'PROMEDFAR SRL'),
  array('pr_id' => '81','pr_razon_social' => 'ATLAS PHARMA'),
  array('pr_id' => '82','pr_razon_social' => 'TELCHI LITEL LTDA.'),
  array('pr_id' => '83','pr_razon_social' => 'ADDAX'),
  array('pr_id' => '84','pr_razon_social' => 'INQUIBOL S.R.L.'),
  array('pr_id' => '85','pr_razon_social' => 'ADDAX INTERNACIONAL'),
  array('pr_id' => '86','pr_razon_social' => 'LABORATORIO REX'),
  array('pr_id' => '87','pr_razon_social' => 'SCHMIDTS PHARMA S.R.L.'),
  array('pr_id' => '88','pr_razon_social' => 'PHARMA SERVICE REPRESENTANTE S.R.L.'),
  array('pr_id' => '89','pr_razon_social' => 'FARMAVAL BOLIVIA S.R.L.'),
  array('pr_id' => '90','pr_razon_social' => 'ENGELS MERKEL Y CIA. (BOLIVIA) S.A.'),
  array('pr_id' => '91','pr_razon_social' => 'A3TEK S.R.L.'),
  array('pr_id' => '92','pr_razon_social' => 'ABD PHARMA'),
  array('pr_id' => '93','pr_razon_social' => 'NEXTCORP S.R.L.'),
  array('pr_id' => '94','pr_razon_social' => 'INMEDENT S.R.L.'),
  array('pr_id' => '95','pr_razon_social' => 'IMPORTADORA F&M SRL'),
  array('pr_id' => '96','pr_razon_social' => 'VALENCIA S.R.L.'),
  array('pr_id' => '97','pr_razon_social' => 'HAHNEMANN S.A.'),
  array('pr_id' => '98','pr_razon_social' => 'PRODEXA LTDA'),
  array('pr_id' => '99','pr_razon_social' => 'SANT DRUG S.R.L.'),
  array('pr_id' => '100','pr_razon_social' => 'ROXELL S.R.L.'),
  array('pr_id' => '101','pr_razon_social' => 'ARGEBOL LTDA.'),
  array('pr_id' => '102','pr_razon_social' => 'IME SRL'),
  array('pr_id' => '103','pr_razon_social' => 'SANAT PHARMA'),
  array('pr_id' => '104','pr_razon_social' => 'RAICES IMPORT EXPORT LTDA'),
  array('pr_id' => '105','pr_razon_social' => 'ROXELL PHARMA S.R.L.'),
  array('pr_id' => '106','pr_razon_social' => 'DELTA S.A.'),
  array('pr_id' => '107','pr_razon_social' => 'KAIS'),
  array('pr_id' => '108','pr_razon_social' => 'CORMESA LTDA.'),
  array('pr_id' => '109','pr_razon_social' => 'TECNOFARMA S.A.'),
  array('pr_id' => '110','pr_razon_social' => 'IMEXFAR S.R.L.'),
  array('pr_id' => '111','pr_razon_social' => 'CAMSA INDUSTRIA COMERCIO S.A.'),
  array('pr_id' => '112','pr_razon_social' => 'COFAR'),
  array('pr_id' => '113','pr_razon_social' => 'PROFARMA-BIT'),
  array('pr_id' => '114','pr_razon_social' => 'NOVOPHARMA'),
  array('pr_id' => '115','pr_razon_social' => 'BIO QUEST SYSTEMS S.R.L.'),
  array('pr_id' => '116','pr_razon_social' => 'APISBOL'),
  array('pr_id' => '117','pr_razon_social' => 'SODIPHAR CORPORATION SRL'),
  array('pr_id' => '118','pr_razon_social' => 'CAMSA SA'),
  array('pr_id' => '119','pr_razon_social' => 'WAWITAS PYG'),
  array('pr_id' => '120','pr_razon_social' => 'DREAMS FACTORY'),
  array('pr_id' => '121','pr_razon_social' => 'DISTRIBUIDORA SALUD VITAL'),
  array('pr_id' => '122','pr_razon_social' => 'OLYMPUS PHARMA S.R.L.'),
  array('pr_id' => '123','pr_razon_social' => 'FARAON'),
  array('pr_id' => '124','pr_razon_social' => 'LCFARMA'),
  array('pr_id' => '125','pr_razon_social' => 'BRIMEG SRL'),
  array('pr_id' => '126','pr_razon_social' => 'PHARMA SERVICE REPRESENTANTES S.R.L.'),
  array('pr_id' => '127','pr_razon_social' => 'HIPOCRATES PHARMA'),
  array('pr_id' => '128','pr_razon_social' => 'RICES IMPORT EXPORT LTDA'),
  array('pr_id' => '129','pr_razon_social' => 'HANSA LTDA.'),
  array('pr_id' => '130','pr_razon_social' => 'VIANPHARMA'),
  array('pr_id' => '131','pr_razon_social' => 'MEGA VIT S.R.L.'),
  array('pr_id' => '132','pr_razon_social' => 'RODAMEDD'),
  array('pr_id' => '133','pr_razon_social' => 'MARQUEZ DERMATOLÓGICA'),
  array('pr_id' => '134','pr_razon_social' => 'MARQUEZ DERMATOLÓGICA'),
  array('pr_id' => '135','pr_razon_social' => 'ADNEFAR SRL.'),
  array('pr_id' => '136','pr_razon_social' => 'LABORATORIOS CRESPAL S.A.'),
  array('pr_id' => '137','pr_razon_social' => 'CORMED'),
  array('pr_id' => '138','pr_razon_social' => 'PICCOLINO'),
  array('pr_id' => '139','pr_razon_social' => 'WAWITAS PYG'),
  array('pr_id' => '140','pr_razon_social' => 'SANUS'),
  array('pr_id' => '141','pr_razon_social' => 'E- FARMA LTDA'),
  array('pr_id' => '142','pr_razon_social' => 'FARMA SHOPPING'),
  array('pr_id' => '143','pr_razon_social' => 'MEGAVIT'),
  array('pr_id' => '144','pr_razon_social' => 'MARKDIS'),
  array('pr_id' => '145','pr_razon_social' => 'SODIPHAR CORPORATION SRL'),
  array('pr_id' => '146','pr_razon_social' => 'LOGMARK ESAPRO S.A.'),
  array('pr_id' => '147','pr_razon_social' => 'PROESA'),
  array('pr_id' => '148','pr_razon_social' => 'DICOM DISTRIBUIDORES DEL ORIENTE SRL'),
  array('pr_id' => '149','pr_razon_social' => 'BABARIA'),
  array('pr_id' => '150','pr_razon_social' => 'HP'),
  array('pr_id' => '151','pr_razon_social' => 'HOSPIMED S.R.L.'),
  array('pr_id' => '152','pr_razon_social' => 'TAMIVA'),
  array('pr_id' => '153','pr_razon_social' => 'ADA-BOLIVIA IMPORT EXPORT'),
  array('pr_id' => '154','pr_razon_social' => 'GLOBAL MEDICAL S.R.L.'),
  array('pr_id' => '155','pr_razon_social' => 'UNILEVER ANDINA BOLIVIA S.A'),
  array('pr_id' => '156','pr_razon_social' => 'BPA FREE'),
  array('pr_id' => '157','pr_razon_social' => 'BRIGHT STARS'),
  array('pr_id' => '158','pr_razon_social' => 'ALMAGRAN S.R.L.'),
  array('pr_id' => '159','pr_razon_social' => 'HAHNEMANN SRL'),
  array('pr_id' => '160','pr_razon_social' => 'MANEK PHARMA'),
  array('pr_id' => '161','pr_razon_social' => 'BIOFARMA S.A.'),
  array('pr_id' => '162','pr_razon_social' => 'MHEDICAL PHARMA S.R.L.'),
  array('pr_id' => '163','pr_razon_social' => 'SANOFI'),
  array('pr_id' => '164','pr_razon_social' => 'KENIT PHARMA'),
  array('pr_id' => '165','pr_razon_social' => 'KRISHPAR CARE BOLIVIA S.R.L'),
  array('pr_id' => '166','pr_razon_social' => 'QUIMIZA LTDA'),
  array('pr_id' => '167','pr_razon_social' => 'INMEDENT SRL'),
  array('pr_id' => '168','pr_razon_social' => 'PHARMA SERVICE REPRESENTANTE S.R.L.'),
  array('pr_id' => '169','pr_razon_social' => 'TORNERO REPRESENTACIONES'),
  array('pr_id' => '170','pr_razon_social' => 'TERBOL'),
  array('pr_id' => '171','pr_razon_social' => 'EMBEXTRA PHARMACEUTICA S.R.L.'),
  array('pr_id' => '172','pr_razon_social' => 'FRATEL S.R.L.'),
  array('pr_id' => '173','pr_razon_social' => 'SANAT PHARMA'),
  array('pr_id' => '174','pr_razon_social' => 'TOTAL MEDIK PHARMA S.R.L.'),
  array('pr_id' => '175','pr_razon_social' => 'KRISHPAR'),
  array('pr_id' => '176','pr_razon_social' => 'DULCEPHARMA SRL'),
  array('pr_id' => '177','pr_razon_social' => 'MINOIL S.A.'),
  array('pr_id' => '178','pr_razon_social' => 'DULCIFARMA'),
  array('pr_id' => '179','pr_razon_social' => 'PHARMICA'),
  array('pr_id' => '180','pr_razon_social' => 'MEGALABS S.R.L.'),
  array('pr_id' => '181','pr_razon_social' => 'laboratorio catedral'),
  array('pr_id' => '182','pr_razon_social' => 'CAMSA INDUSTRIA Y COMERCIO S.A.'),
  array('pr_id' => '183','pr_razon_social' => 'GARDEN-BRI'),
  array('pr_id' => '184','pr_razon_social' => 'SECURITY MEDICINE BOLIVIA'),
  array('pr_id' => '185','pr_razon_social' => 'LOGMARK'),
  array('pr_id' => '186','pr_razon_social' => 'SALUD VITAL'),
  array('pr_id' => '187','pr_razon_social' => 'CAMERA'),
  array('pr_id' => '188','pr_razon_social' => 'VARCERO'),
  array('pr_id' => '189','pr_razon_social' => 'IMPORTADORA F&M SRL'),
  array('pr_id' => '190','pr_razon_social' => 'MEGALAB BOLIVIA S.R.L.'),
  array('pr_id' => '191','pr_razon_social' => 'LEMAITRE S.R.L.'),
  array('pr_id' => '192','pr_razon_social' => 'CAMSA'),
  array('pr_id' => '193','pr_razon_social' => 'QUIFARNAT'),
  array('pr_id' => '194','pr_razon_social' => 'FOODWELL SRL.'),
  array('pr_id' => '195','pr_razon_social' => 'QUIFARNAT'),
  array('pr_id' => '196','pr_razon_social' => 'VITAVEC'),
  array('pr_id' => '197','pr_razon_social' => 'PROALPAZ'),
  array('pr_id' => '198','pr_razon_social' => 'FOOD WELL'),
  array('pr_id' => '199','pr_razon_social' => 'FARAON'),
  array('pr_id' => '200','pr_razon_social' => 'BAYER BOLIVIANA LTDA'),
  array('pr_id' => '201','pr_razon_social' => 'JEZREEL MEDIC'),
  array('pr_id' => '202','pr_razon_social' => 'LABORATORIO SANDERSON S.A.'),
  array('pr_id' => '203','pr_razon_social' => 'LA BORATORIOS ABD'),
  array('pr_id' => '204','pr_razon_social' => 'SANAMEDIC'),
  array('pr_id' => '205','pr_razon_social' => 'COSIN LTDA.'),
  array('pr_id' => '206','pr_razon_social' => 'NOSTAS S.R.L.'),
  array('pr_id' => '207','pr_razon_social' => 'IVANKA S.R.L.'),
  array('pr_id' => '208','pr_razon_social' => 'TELCHI LITEL'),
  array('pr_id' => '209','pr_razon_social' => 'KINESIA PHARMA'),
  array('pr_id' => '210','pr_razon_social' => 'SATELITE'),
  array('pr_id' => '211','pr_razon_social' => 'INMED F.C.'),
  array('pr_id' => '212','pr_razon_social' => 'ADDAX'),
  array('pr_id' => '213','pr_razon_social' => 'COLORS'),
  array('pr_id' => '214','pr_razon_social' => 'ATLAS PHARMA'),
  array('pr_id' => '215','pr_razon_social' => 'SAE'),
  array('pr_id' => '216','pr_razon_social' => 'ALMACEN'),
  array('pr_id' => '217','pr_razon_social' => 'FABRA S.A'),
  array('pr_id' => '218','pr_razon_social' => 'MINERVA'),
  array('pr_id' => '219','pr_razon_social' => 'BOTICA'),
  array('pr_id' => '220','pr_razon_social' => 'ROSSI'),
  array('pr_id' => '221','pr_razon_social' => 'PHARMA SERVICE'),
  array('pr_id' => '222','pr_razon_social' => 'GAMBOA LTDA.'),
  array('pr_id' => '223','pr_razon_social' => 'SMEFAR'),
  array('pr_id' => '224','pr_razon_social' => 'MARCONI'),
  array('pr_id' => '225','pr_razon_social' => 'APISBOL SRL'),
  array('pr_id' => '226','pr_razon_social' => 'TOKALAN'),
  array('pr_id' => '227','pr_razon_social' => 'A.B.D INDUS. DE PRODUC. FARMACEU. LTDA'),
  array('pr_id' => '228','pr_razon_social' => 'GYLMAR PHARMA'),
  array('pr_id' => '229','pr_razon_social' => 'AGRONAT S.A.'),
  array('pr_id' => '230','pr_razon_social' => 'PHARMACEUTICALS PVT. LTD.'),
  array('pr_id' => '231','pr_razon_social' => 'ABAD PHARMA S.R.L'),
  array('pr_id' => '232','pr_razon_social' => 'LA SANTE'),
  array('pr_id' => '233','pr_razon_social' => 'FARAON S.R.L'),
  array('pr_id' => '234','pr_razon_social' => 'PHARMABRICH S.R.L.'),
  array('pr_id' => '235','pr_razon_social' => 'LC PHARMA'),
  array('pr_id' => '236','pr_razon_social' => 'JEZREEL MEDIC'),
  array('pr_id' => '237','pr_razon_social' => 'MHEDICAL PHARMA'),
  array('pr_id' => '238','pr_razon_social' => 'IMBOLMED (IMPORT. BOLIVIANA DE MEDICAMENTOS)'),
  array('pr_id' => '239','pr_razon_social' => 'HAHNEMANN SRL.'),
  array('pr_id' => '240','pr_razon_social' => 'SANAT PHARMA'),
  array('pr_id' => '241','pr_razon_social' => 'LABORATORIOS VITA S.A'),
  array('pr_id' => '242','pr_razon_social' => 'PHARMATECH BOLIVIANA S.A.'),
  array('pr_id' => '243','pr_razon_social' => 'SOCOMAN  S.A.'),
  array('pr_id' => '244','pr_razon_social' => 'DULCIFARMA SRL'),
  array('pr_id' => '245','pr_razon_social' => 'KRISPAR'),
  array('pr_id' => '246','pr_razon_social' => 'SODIPHAR CORPORATION S.R.L.'),
  array('pr_id' => '247','pr_razon_social' => 'ROXELL PHARMA S.R.L.'),
  array('pr_id' => '248','pr_razon_social' => 'SODIPHAR CORPORATION S.R.L.'),
  array('pr_id' => '249','pr_razon_social' => 'SANTIAFAR S.R.L.'),
  array('pr_id' => '250','pr_razon_social' => '3M CHILE S.A.SUCURSAL1 BOLIVIA'),
  array('pr_id' => '251','pr_razon_social' => 'AISAFARM S.R.L.'),
  array('pr_id' => '252','pr_razon_social' => 'INDUSTRIA QUIMICA BOLIVIANA "INQUIBOL"'),
  array('pr_id' => '253','pr_razon_social' => 'GEO FARMA S.R.L.'),
  array('pr_id' => '254','pr_razon_social' => 'HAHNEMANN'),
  array('pr_id' => '255','pr_razon_social' => 'IFA S.A.'),
  array('pr_id' => '256','pr_razon_social' => 'BRIMEG'),
  array('pr_id' => '257','pr_razon_social' => 'FULL PHARMA'),
  array('pr_id' => '258','pr_razon_social' => 'CR FARMA S.R.L.'),
  array('pr_id' => '259','pr_razon_social' => 'BODECO S.R.L.'),
  array('pr_id' => '260','pr_razon_social' => 'KENIT PHARMA'),
  array('pr_id' => '261','pr_razon_social' => 'ABL PHARMA BOLIVIA LTDA.'),
  array('pr_id' => '262','pr_razon_social' => 'FASE GLOBAL'),
  array('pr_id' => '263','pr_razon_social' => 'FASEFLEX GLOBAL'),
  array('pr_id' => '264','pr_razon_social' => 'DR. MEDINAT CBBA'),
  array('pr_id' => '265','pr_razon_social' => 'DR. MEDINAT CBBA'),
  array('pr_id' => '266','pr_razon_social' => 'TECNO MEDICAL BOLIVIA'),
  array('pr_id' => '267','pr_razon_social' => 'PHARMA SERVICE REPRESENTANTES S.R.L'),
  array('pr_id' => '268','pr_razon_social' => 'SAN FERNANDO SRL.'),
  array('pr_id' => '269','pr_razon_social' => 'FARMA SHOPPING'),
  array('pr_id' => '270','pr_razon_social' => 'SAE S.A'),
  array('pr_id' => '271','pr_razon_social' => 'GRUPO EMPRESARIAL VALENCIA S.R.L.'),
  array('pr_id' => '272','pr_razon_social' => 'GRUPO EMPRESARIAL VALENCIA S.R.L'),
  array('pr_id' => '273','pr_razon_social' => 'ESFASA'),
  array('pr_id' => '274','pr_razon_social' => 'COMPANEX BOLIVIA S.A.'),
  array('pr_id' => '275','pr_razon_social' => 'ADDAX INTERNACIONAL'),
  array('pr_id' => '276','pr_razon_social' => 'MEGA VIT'),
  array('pr_id' => '277','pr_razon_social' => 'SOTTCOR LABS S.A.C.'),
  array('pr_id' => '278','pr_razon_social' => 'SOTTCOR'),
  array('pr_id' => '279','pr_razon_social' => 'SOTTCOR'),
  array('pr_id' => '280','pr_razon_social' => 'BELMED LTDA.'),
  array('pr_id' => '281','pr_razon_social' => 'MEQUIBOL PHARMA S.R.L'),
  array('pr_id' => '282','pr_razon_social' => 'ALFA S.A.'),
  array('pr_id' => '283','pr_razon_social' => 'LABORATORIOS ABD LTDA'),
  array('pr_id' => '284','pr_razon_social' => 'KIMBERLY BOLIVIA S.A.'),
  array('pr_id' => '285','pr_razon_social' => 'LABOFTA S.R.L.'),
  array('pr_id' => '286','pr_razon_social' => 'TUDISMED S.R.L.'),
  array('pr_id' => '287','pr_razon_social' => 'INFAN-TEC'),
  array('pr_id' => '288','pr_razon_social' => 'EMBEXTRA S.R.L.'),
  array('pr_id' => '289','pr_razon_social' => 'VIASANA'),
  array('pr_id' => '290','pr_razon_social' => 'ISSUE GROUP BOLIVIA S.R.L.'),
  array('pr_id' => '291','pr_razon_social' => 'APISBOL SRL'),
  array('pr_id' => '292','pr_razon_social' => 'SALUR S.R.L.'),
  array('pr_id' => '293','pr_razon_social' => 'VITAVEC'),
  array('pr_id' => '294','pr_razon_social' => 'OMANEK PHARMA'),
  array('pr_id' => '295','pr_razon_social' => 'ABOL LTDA'),
  array('pr_id' => '296','pr_razon_social' => 'DRENACATH'),
  array('pr_id' => '297','pr_razon_social' => 'LATINOAMERICANOS "LATIN MED"'),
  array('pr_id' => '298','pr_razon_social' => 'CENTRAL DE ABASTECIMIENTO DE SUMINISTRO-CEASS'),
  array('pr_id' => '299','pr_razon_social' => 'KIDIEE'),
  array('pr_id' => '300','pr_razon_social' => 'PROESA PROMOTORA DE EVENTOS S.A.'),
  array('pr_id' => '301','pr_razon_social' => 'OTROS'),
  array('pr_id' => '302','pr_razon_social' => 'LANSINOH'),
  array('pr_id' => '303','pr_razon_social' => 'CORMESA LTDA'),
  array('pr_id' => '304','pr_razon_social' => 'CORMESA LTDA'),
  array('pr_id' => '305','pr_razon_social' => 'CORMESA'),
  array('pr_id' => '306','pr_razon_social' => 'MEGA VIT SRL'),
  array('pr_id' => '307','pr_razon_social' => 'SOUTH AMERI.PHARMACEUTICAL INDUSTRIES(SAPHI)'),
  array('pr_id' => '308','pr_razon_social' => 'PFIZER BOLIVIA S.A.'),
  array('pr_id' => '309','pr_razon_social' => 'HAHNEMANN'),
  array('pr_id' => '310','pr_razon_social' => 'TELCHI - LITEL LTDA'),
  array('pr_id' => '311','pr_razon_social' => 'LUKI TEX'),
  array('pr_id' => '312','pr_razon_social' => 'COSMENAT'),
  array('pr_id' => '313','pr_razon_social' => 'PHARMABRICH S.R.L'),
  array('pr_id' => '314','pr_razon_social' => 'LABORATORIOS EUROFARMA BOLIVIA S.A.'),
  array('pr_id' => '315','pr_razon_social' => 'BOLIVIANA MERCANTIL "SABIA" S.R.L'),
  array('pr_id' => '316','pr_razon_social' => 'PHAMAGEN'),
  array('pr_id' => '317','pr_razon_social' => 'CAMSA S.A.'),
  array('pr_id' => '318','pr_razon_social' => 'ABD PHARMA'),
  array('pr_id' => '319','pr_razon_social' => 'HAHNEMANN SRL'),
  array('pr_id' => '320','pr_razon_social' => 'LABORATORIOS ABD LTDA.'),
  array('pr_id' => '321','pr_razon_social' => 'MEDICPAK'),
  array('pr_id' => '322','pr_razon_social' => 'DISTRIBUIDORA MARTIN'),
  array('pr_id' => '323','pr_razon_social' => 'DISTRIBUIDORA SALUD VITAL'),
  array('pr_id' => '324','pr_razon_social' => 'LA TOY'),
  array('pr_id' => '325','pr_razon_social' => 'OSITOLANDIA'),
  array('pr_id' => '326','pr_razon_social' => 'BIOLATINA S.R.L'),
  array('pr_id' => '327','pr_razon_social' => 'PROALPAZ'),
  array('pr_id' => '328','pr_razon_social' => 'FARMACO S.R.L.'),
  array('pr_id' => '329','pr_razon_social' => 'NEXTCORP'),
  array('pr_id' => '330','pr_razon_social' => 'PHARMAGEN'),
  array('pr_id' => '331','pr_razon_social' => 'LABOFTA S.R.L.'),
  array('pr_id' => '332','pr_razon_social' => 'NEW'),
  array('pr_id' => '333','pr_razon_social' => 'NEX CARE'),
  array('pr_id' => '334','pr_razon_social' => 'BEIERSDORF S.R.L'),
  array('pr_id' => '335','pr_razon_social' => 'THAIS LTDA.'),
  array('pr_id' => '336','pr_razon_social' => 'TOR TRADE ON ROUTE'),
  array('pr_id' => '337','pr_razon_social' => 'AMORCA S.R.L.'),
  array('pr_id' => '338','pr_razon_social' => 'LOGMARK ESAPRO'),
  array('pr_id' => '339','pr_razon_social' => 'DISPROFARMA VIA S.R.L.'),
  array('pr_id' => '340','pr_razon_social' => 'PROMEDICAL'),
  array('pr_id' => '341','pr_razon_social' => 'BUTRON MARINO SOLEDAD VANESSA'),
  array('pr_id' => '342','pr_razon_social' => 'ANION IMPORTACIONES'),
  array('pr_id' => '343','pr_razon_social' => 'TORRICO ANTELO S.R.L'),
  array('pr_id' => '344','pr_razon_social' => 'LOGMARK'),
  array('pr_id' => '345','pr_razon_social' => 'WM & C SRL'),
  array('pr_id' => '346','pr_razon_social' => 'LABORATORIOS VITA S.A'),
  array('pr_id' => '347','pr_razon_social' => 'CHELESPHAR'),
  array('pr_id' => '348','pr_razon_social' => 'FORJAR IMP. EXP. S.R.L.'),
  array('pr_id' => '349','pr_razon_social' => 'INDUSTRIAS TORRICO ANTELO S.R.L.'),
  array('pr_id' => '350','pr_razon_social' => 'HANIEL-FARMED'),
  array('pr_id' => '351','pr_razon_social' => 'QMPHARMA QUALYTI MEDICINE S.R.L.'),
  array('pr_id' => '352','pr_razon_social' => 'DISTRIBUIDORA SALUD VITAL'),
  array('pr_id' => '353','pr_razon_social' => 'MARGARITA SUSANA S.R.L.'),
  array('pr_id' => '354','pr_razon_social' => 'ALGABO'),
  array('pr_id' => '355','pr_razon_social' => 'AVENT'),
  array('pr_id' => '356','pr_razon_social' => 'CHELESPHAR'),
  array('pr_id' => '357','pr_razon_social' => 'LOMARGK ESAPRO SA'),
  array('pr_id' => '358','pr_razon_social' => 'GEDESA LTDA'),
  array('pr_id' => '359','pr_razon_social' => 'MY BABY'),
  array('pr_id' => '360','pr_razon_social' => 'ROMEDD'),
  array('pr_id' => '361','pr_razon_social' => 'SOLQUIFAR S.R.L.'),
  array('pr_id' => '362','pr_razon_social' => 'KEOPS'),
  array('pr_id' => '363','pr_razon_social' => 'SANT DRUG  S.R.L.'),
  array('pr_id' => '364','pr_razon_social' => 'ASOFAR'),
  array('pr_id' => '365','pr_razon_social' => 'IVANKA S.R.L.'),
  array('pr_id' => '366','pr_razon_social' => 'MEGALAB'),
  array('pr_id' => '367','pr_razon_social' => 'FRATEL S.R.L'),
  array('pr_id' => '368','pr_razon_social' => 'CORMESA'),
  array('pr_id' => '369','pr_razon_social' => 'MHEDICAL PHARMA S.R.L')
);
